# Generated by Django 2.2.4 on 2019-08-25 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190819_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='greyfish_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
