# Generated by Django 2.2.5 on 2019-11-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceti_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cetijobs',
            name='dir_used',
        ),
        migrations.AddField(
            model_name='cetijobs',
            name='script_file',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cetijobs',
            name='finished_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cetijobs',
            name='latest_run',
            field=models.DateTimeField(blank=True),
        ),
    ]
