# Generated by Django 2.2.5 on 2020-01-14 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceti_jobs', '0003_cetijobs_dir_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cetijobs',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cetijobs',
            name='latest_run',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cetijobs',
            name='node',
            field=models.TextField(blank=True, default=0),
        ),
    ]
